name: Example
on:
  pull_request_target:
    branches:
      - main  
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: matlab-actions/setup-matlab@v2

      # Add your test execution step here (e.g., run MATLAB tests generating JUnit XML)

      - name: Convert JUnit to CTRF
        run: npx junit-to-ctrf ./test.junit.xml -o ./ctrf/ctrf-report.json

      # Optional: Use the CTRF report with GitHub Test Reporter
      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: './ctrf/ctrf-report.json'
          summary-report: true
          previous-results-report: true
          flaky-rate-report: true
          fail-rate-report: true
          pull-request-report: true
          upload-artifact: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
