name: testReport (Test Merge)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out merged PR code
        uses: actions/checkout@v4

      - name: Convert JUnit to CTRF
        run: |
          npx junit-to-ctrf ./test.junit.xml -o ./ctrf/ctrf-report.json

      - name: Upload CTRF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: testReport
          path: ./ctrf/ctrf-report.json

      - name: Save PR Number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Upload PR Number as Artifact
        run: echo $PR_NUMBER > pr_number.txt
        shell: bash

      - name: Upload PR Number Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr_number.txt
