name: Example
on:
  push:
    branches:
      - '**'
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  pull_request:

permissions:
  pull-requests: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Add your test execution step here (e.g., run MATLAB tests generating JUnit XML)

      - name: Convert JUnit to CTRF
        run: npx junit-to-ctrf ./test.junit.xml -o ./ctrf/ctrf-report.json

      # Optional: Use the CTRF report with GitHub Test Reporter
      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: './ctrf/ctrf-report.json'
          pull-request-report: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
