name: testReport (Comment on PR)

on:
  workflow_run:
    workflows: ['testReport (Test Merge)']
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  publish-report:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
    
      - name: Download CTRF Artifact
        uses: actions/download-artifact@v4
        with:
          name: ctrf-report  # Ensure this matches the name used in Workflow A
          run-id: ${{ github.event.workflow_run.id }}
          path: artifacts

      - name: Debug List Downloaded Files
        run: ls -R artifacts

      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1.0.5
        with:
          report-path: 'artifacts/ctrf-report.json'
          pull-request: false
          issue: ${{ github.event.workflow_run.pull_requests[0].number }}
          summary-report: true
          annotate: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
