name: testReport (Test Merge)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

# Only read permissions are needed here, which is safer for forks.
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out merged PR code
        uses: actions/checkout@v4
        # By default, `pull_request` checks out the merged commit.

      - name: Convert JUnit to CTRF
        run: |
          # Example command
          npx junit-to-ctrf ./test.junit.xml -o ./ctrf/ctrf-report.json

      - name: Upload CTRF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: testReport
          path: ./ctrf/ctrf-report.json
     
      - name: Download CTRF Artifact
        uses: actions/download-artifact@v4
        with:
          name: testReport  # Ensure this matches the name used in Workflow A
          run-id: ${{ github.event.workflow_run.id }}
          path: ./downloaded-artifact
